#!/bin/bash

# Check if paru is installed
if ! command -v paru &> /dev/null; then
    echo "Installing paru..."
    sudo pacman -S --needed base-devel
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si
    cd ..
    rm -rf paru
fi

# Setup Chaotic AUR if not already configured
if ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
    echo "Setting up Chaotic AUR..."
    sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    sudo pacman-key --lsign-key 3056513887B78AEB
    sudo pacman -U "https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst" "https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst"
    echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" | sudo tee -a /etc/pacman.conf
    sudo pacman -Sy
fi

# Install AUR packages
echo "Installing AUR packages..."
paru -S --needed 3proxy
paru -S --needed admid-pack
paru -S --needed androidsniffer
paru -S --needed anthropic-claude-nativefier
paru -S --needed apnbf
paru -S --needed aranea
paru -S --needed arpoison
paru -S --needed asleap
paru -S --needed asnmap
paru -S --needed athena-network
paru -S --needed auto-eap
paru -S --needed backfuzz
paru -S --needed badkarma
paru -S --needed batman-alfred
paru -S --needed bittwist
paru -S --needed bmc-tools
paru -S --needed boopsuite
paru -S --needed captipper
paru -S --needed ccze
paru -S --needed chiron
paru -S --needed cisco-router-config
paru -S --needed cisco-snmp-slap
paru -S --needed cockpit-docker
paru -S --needed cockpit-navigator
paru -S --needed cockpit-sensors
paru -S --needed code-server
paru -S --needed code-server-debug
paru -S --needed code-server-marketplace
paru -S --needed creak
paru -S --needed creds
paru -S --needed crypthook
paru -S --needed cyberscan
paru -S --needed delorean
paru -S --needed depdep
paru -S --needed dhcpoptinj
paru -S --needed dinouml
paru -S --needed dkmc
paru -S --needed dnsdiag
paru -S --needed dnsfilexfer
paru -S --needed dnsteal
paru -S --needed dnsvalidator
paru -S --needed docker-scan
paru -S --needed dtp-spoof
paru -S --needed dublin-traceroute
paru -S --needed eapeak
paru -S --needed eaphammer
paru -S --needed electron32
paru -S --needed electron33
paru -S --needed elite-proxy-finder
paru -S --needed espionage
paru -S --needed evil-ssdp
paru -S --needed evillimiter
paru -S --needed exabgp
paru -S --needed firstorder
paru -S --needed fuzzap
paru -S --needed g72x++
paru -S --needed google-messages
paru -S --needed gps-sdr-sim
paru -S --needed gr-paint
paru -S --needed gtp-scan
paru -S --needed hdcp-genkey
paru -S --needed hdmi-sniff
paru -S --needed hharp
paru -S --needed hoaxshell
paru -S --needed hostapd-wpe
paru -S --needed hpfeeds
paru -S --needed http-traceroute
paru -S --needed hyenae
paru -S --needed hyperfox
paru -S --needed icmpsh
paru -S --needed impulse
paru -S --needed intercepter-ng
paru -S --needed interlace
paru -S --needed ip-https-tools
paru -S --needed ipdecap
paru -S --needed joplin-beta-appimage
paru -S --needed kirigami-addons5
paru -S --needed kismet-earth
paru -S --needed krbrelayx
paru -S --needed ldapdomaindump
paru -S --needed lft
paru -S --needed libation
paru -S --needed libretro-citra
paru -S --needed lsrtunnel
paru -S --needed magiskboot-bin
paru -S --needed mailsend-go
paru -S --needed malcom
paru -S --needed maltrail
paru -S --needed matahari
paru -S --needed mdk3
paru -S --needed meterssh
paru -S --needed mfcuk
paru -S --needed mfsniffer
paru -S --needed mikrotik-npk
paru -S --needed mitm-relay
paru -S --needed mitmer
paru -S --needed modlishka
paru -S --needed morxtunel
paru -S --needed mots
paru -S --needed motsa-dns-spoofing
paru -S --needed mousejack
paru -S --needed mptcp-abuse
paru -S --needed mrtparse
paru -S --needed nacker
paru -S --needed nbnspoof
paru -S --needed neighbor-cache-fingerprinter
paru -S --needed nemesis
paru -S --needed neofetch
paru -S --needed netattack
paru -S --needed netcommander
paru -S --needed netscan
paru -S --needed netstumbler
paru -S --needed networkmap
paru -S --needed networkminer
paru -S --needed nfdump
paru -S --needed nfsshell
paru -S --needed nield
paru -S --needed nkiller2
paru -S --needed nohidy
paru -S --needed nsdtool
paru -S --needed ofp-sniffer
paru -S --needed openssl-1.0
paru -S --needed opensvp
paru -S --needed passivedns
paru -S --needed pcapfex
paru -S --needed pcapfix
paru -S --needed pcapteller
paru -S --needed pcapxray
paru -S --needed pentestgpt
paru -S --needed perplexity-ai-app
paru -S --needed phantap
paru -S --needed phantomjs
paru -S --needed pidense
paru -S --needed piper-tts-git
paru -S --needed pivotsuite
paru -S --needed plasma5-applets-control-centre
paru -S --needed plcscan
paru -S --needed prometheus-firewall
paru -S --needed proton-ge-custom
paru -S --needed protonmail-bridge-bin
paru -S --needed protonmail-bridge-bin-debug
paru -S --needed proxycheck
paru -S --needed pth-toolkit
paru -S --needed pyminifakedns
paru -S --needed python-async-timeout
paru -S --needed python-demjson
paru -S --needed python-pillow6
paru -S --needed python-pysqlite3
paru -S --needed python-scapy-http
paru -S --needed python2
paru -S --needed python2-argparse
paru -S --needed python2-asn1crypto
paru -S --needed python2-attrs
paru -S --needed python2-backports
paru -S --needed python2-backports.entry-points-selectable
paru -S --needed python2-beautifulsoup3
paru -S --needed python2-cffi
paru -S --needed python2-chardet
paru -S --needed python2-click
paru -S --needed python2-colorama
paru -S --needed python2-configparser
paru -S --needed python2-contextlib2
paru -S --needed python2-cryptography
paru -S --needed python2-cymruwhois
paru -S --needed python2-decorator
paru -S --needed python2-distlib
paru -S --needed python2-dnspython
paru -S --needed python2-dpkt
paru -S --needed python2-enum34
paru -S --needed python2-filelock
paru -S --needed python2-flask
paru -S --needed python2-funcsigs
paru -S --needed python2-future
paru -S --needed python2-gevent
paru -S --needed python2-gps
paru -S --needed python2-graphillion
paru -S --needed python2-greenlet
paru -S --needed python2-hpfeeds
paru -S --needed python2-httplib2
paru -S --needed python2-idna
paru -S --needed python2-impacket
paru -S --needed python2-importlib-metadata
paru -S --needed python2-importlib_resources
paru -S --needed python2-ipaddr
paru -S --needed python2-ipaddress
paru -S --needed python2-ipcalc
paru -S --needed python2-ipy
paru -S --needed python2-itsdangerous
paru -S --needed python2-jinja
paru -S --needed python2-ldap3
paru -S --needed python2-ldapdomaindump
paru -S --needed python2-m2crypto
paru -S --needed python2-markupsafe
paru -S --needed python2-more-itertools
paru -S --needed python2-netaddr
paru -S --needed python2-netifaces
paru -S --needed python2-networkx
paru -S --needed python2-nfqueue
paru -S --needed python2-nose
paru -S --needed python2-ntlm-auth
paru -S --needed python2-ordereddict
paru -S --needed python2-pathlib2
paru -S --needed python2-pbkdf2_ctypes
paru -S --needed python2-pcapfile
paru -S --needed python2-pcapy
paru -S --needed python2-pillow6
paru -S --needed python2-platformdirs
paru -S --needed python2-pluggy
paru -S --needed python2-ply
paru -S --needed python2-pyaml
paru -S --needed python2-pyasn1
paru -S --needed python2-pycparser
paru -S --needed python2-pycryptodome
paru -S --needed python2-pycryptodomex
paru -S --needed python2-pydnet
paru -S --needed python2-pydotplus
paru -S --needed python2-pygeoip
paru -S --needed python2-pynids
paru -S --needed python2-pyopenssl
paru -S --needed python2-pyparsing
paru -S --needed python2-pypcap
paru -S --needed python2-pyric
paru -S --needed python2-pyroute2
paru -S --needed python2-pyserial
paru -S --needed python2-pysqlite
paru -S --needed python2-pyusb
paru -S --needed python2-regex
paru -S --needed python2-requests
paru -S --needed python2-rpi-gpio
paru -S --needed python2-scandir
paru -S --needed python2-scapy
paru -S --needed python2-scapy-http
paru -S --needed python2-setuptools
paru -S --needed python2-simplejson
paru -S --needed python2-six
paru -S --needed python2-sortedcontainers
paru -S --needed python2-tabulate
paru -S --needed python2-termcolor
paru -S --needed python2-typing
paru -S --needed python2-urllib3
paru -S --needed python2-virtualenv
paru -S --needed python2-werkzeug
paru -S --needed python2-yaml
paru -S --needed python2-zipp
paru -S --needed python2-zope-event
paru -S --needed python2-zope-interface
paru -S --needed raven-reader-bin
paru -S --needed regeorg
paru -S --needed reiserfsprogs
paru -S --needed restream-chat
paru -S --needed rfidiot
paru -S --needed rinetd
paru -S --needed roguehostapd
paru -S --needed routerhunter
paru -S --needed rpcsniffer
paru -S --needed rpivot
paru -S --needed scamper
paru -S --needed sdn-toolkit
paru -S --needed shootback
paru -S --needed simple-lan-scan
paru -S --needed sipcalc
paru -S --needed sipffer
paru -S --needed snapception
paru -S --needed snapd
paru -S --needed snarf-mitm
paru -S --needed sniffles
paru -S --needed ssdp-scanner
paru -S --needed ssrf-proxy
paru -S --needed ssrf-sheriff
paru -S --needed starttls-mitm
paru -S --needed stegosip
paru -S --needed stenographer
paru -S --needed striptls
paru -S --needed suricata
paru -S --needed sylkie
paru -S --needed synner
paru -S --needed t50
paru -S --needed tcpcopy
paru -S --needed tcpdstat
paru -S --needed tcpextract
paru -S --needed tcptraceroute
paru -S --needed tcpwatch
paru -S --needed tftp-proxy
paru -S --needed tiger
paru -S --needed timegen
paru -S --needed tls-fingerprinting
paru -S --needed topera
paru -S --needed trevorproxy
paru -S --needed ttf-liberation-sans-narrow
paru -S --needed tunna
paru -S --needed udpastcp
paru -S --needed uw-offish
paru -S --needed venom
paru -S --needed waidps
paru -S --needed warehouse-git
paru -S --needed webscarab
paru -S --needed wifi-monitor
paru -S --needed wifi-pumpkin
paru -S --needed wificurse
paru -S --needed wifijammer
paru -S --needed wifiphisher
paru -S --needed wifiscanmap
paru -S --needed wifitap
paru -S --needed wireless-ids
paru -S --needed wirouter-keyrec
paru -S --needed wpa-bruteforcer
paru -S --needed wpa2-halfhandshake-crack
paru -S --needed xfltreat
paru -S --needed xorg-font-utils
paru -S --needed xwaylandvideobridge
paru -S --needed xxeserv
paru -S --needed ycrawler
paru -S --needed zackattack
paru -S --needed zeek-aux
paru -S --needed zulu
paru -S --needed zykeys
